name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Deploy to Heroku
        runs-on: ubuntu-latest
        steps:
            - name: Clone the repository
              uses: actions/checkout@v2

            - name: Build and Push the Docker image to Heroku Container Registry
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                  heroku_email: ${{ secrets.HEROKU_EMAIL }}
                  dockerfile_path: "RestaurantManagement"
